[package]
name = "ncalendar"
version = "0.1.0"
edition = "2021"

[lib]
name = "ncalendar"
path = "src/lib/mod.rs"

[[bin]]
name = "ncalendar"
path = "src/main.rs"

[dependencies]
nom = "7.1.1"
structopt = "0.3.26"
time = { version = "0.3.17", features = ["local-offset"] }
